### PR TITLE
API w/ GPT

### PR DESCRIPTION
**Pull request by borhara**
This PR will merge GPT 3.5 functionality.

- Exceptions.py was removed and now just returns HTTP exceptions
- The handler validates the request body
- Response.py passes through instruction prompts with user context gathered from questions

### CODE REVIEW

**Comment by borhara** [comment]
I'll add an example request soon, but I'll make some form of documentation later.

**Comment by salehudeen** [comment]
pr agreed

**Review by SwyftPain — APPROVED** [review]
Nice. I like the idea of using mongo as well.

**Review by David06A — APPROVED** [review]

**Comment by David06A** [comment]
Common Shiv W

**Pull request merged**
