### PR TITLE
Feature/home page

### PR DESCRIPTION
**Pull request by David06A**
Implements: 

- The new home page
- Dark and Light mode toggle
- Page layout

https://user-images.githubusercontent.com/74801783/222308799-d26dadcb-eb4e-4faf-9152-9a9880190e59.mp4

### CODE REVIEW

**Comment by David06A** [comment]
#6 
#1

**Comment by David06A** [comment]
https://user-images.githubusercontent.com/74801783/224440359-a5d43e23-241e-4270-9157-0af416ddc8bf.mp4

**Review by SwyftPain — APPROVED** [review]
I feel like you did a lot for a single PR, personally not a fan of the light gray color on the light mode but that aside, code wise, everything is fine. 

The color is just personal opinion, so approved either way.

**Comment by David06A** [comment]
> I feel like you did a lot for a single PR, personally not a fan of the light gray color on the light mode but that aside, code wise, everything is fine.
> 
> The color is just personal opinion, so approved either way.

Yeah found it hard to work with, the pallet colours we chose weren't easy lmao

**Review by borhara — APPROVED** [review]
I like the theme.

**Pull request merged**
